force-app/main/default/objects/Google_Address_Finder_Setting__mdt/Google_Address_Finder_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for the GoogleAddressFinderEnhanced Component</description>
    <label>Google Address Finder Setting</label>
    <pluralLabel>Google Address Finder Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Google_Address_Finder_Setting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>Google API Key to be able to use the APIs.
Help: https://developers.google.com/maps/documentation/places/web-service/get-api-key</description>
    <inlineHelpText>Google API Key to be able to use the APIs.</inlineHelpText>
    <label>API Key</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Address_Finder_Setting__mdt/fields/Place_Autocomplete_URL__c.field-meta.xml
<CustomField>
    <fullName>Place_Autocomplete_URL__c</fullName>
    <description>URL for the Google Place Autocomplete Endpoint. 
Help: https://developers.google.com/maps/documentation/places/web-service/autocomplete</description>
    <inlineHelpText>URL for the Google Place Autocomplete Endpoint.</inlineHelpText>
    <label>Place Autocomplete URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Google_Address_Finder_Setting__mdt/fields/Place_Details_URL__c.field-meta.xml
<CustomField>
    <fullName>Place_Details_URL__c</fullName>
    <description>URL for the Google Place Details Endpoint. 
Help: https://developers.google.com/maps/documentation/places/web-service/details</description>
    <inlineHelpText>URL for the Google Place Details Endpoint.</inlineHelpText>
    <label>Place Details URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/GoogleAddressFinderController.cls
/*************************************************************************************************************
 * @name			GoogleAddressFinderController
 * @author			Pablo Martinez <ing.martinez.pablo@gmail.com>
 * @created			04 / 09 / 2022
 * @description		Class to manage the Google Address Finder Enhanced LWC
 * @TestClass		GoogleAddressFinderControllerTest
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 * 				No.		Date			Author					Description
 * 				----	------------	--------------------	----------------------------------------------
 * @version		1.0		2022-09-04		Pablo Martinez			Creation of the class
 *
 **************************************************************************************************************/
public with sharing class GoogleAddressFinderController {
  private static Google_Address_Finder_Setting__mdt settings = Google_Address_Finder_Setting__mdt.getInstance(
    'Places_API'
  );

  /*********************************************************************************************************
   * @name			doCallout
   * @author			Pablo Martinez <ing.martinez.pablo@gmail.com>
   * @created			04 / 09 / 2022
   * @description		Method that does the GET callout to the specified endpoint
   * @param			String endpoint : the endpoint to call
   * @return			Response wrapper with the isSuccess flag, errorMessage (if any) and the data from the callout response
   **********************************************************************************************************/
  private static Response doCallout(String endpoint) {
    Response theResponse = new Response();

    Http http = new Http();
    HttpRequest request = new HttpRequest();

    request.setMethod('GET');
    request.setEndpoint(endpoint + '&key=' + settings.API_Key__c);
    request.setTimeout(120000);
    HttpResponse response = http.send(request);

    Map<String, Object> parsedResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());

    // success
    if (response.getStatusCode() == 200) {
      if (((String) parsedResponse.get('status')) == 'OK') {
        theResponse.isSuccess = true;
        theResponse.errorMessage = null;
        theResponse.data = response.getBody();
      } else {
        theResponse.isSuccess = false;
        theResponse.data = null;
        theResponse.errorMessage = (String) parsedResponse.get('error_message');
      }
    } else {
      theResponse.isSuccess = false;
      theResponse.data = null;
      theResponse.errorMessage = response.getBody();
    }

    return theResponse;
  }

  /*********************************************************************************************************
   * @name			getAddresses
   * @author			Pablo Martinez <ing.martinez.pablo@gmail.com>
   * @created			04 / 09 / 2022
   * @description		Get a list of matching addresses given a search text and filters
   * @param			String searchText : the text to search for
   * @param			String sessionToken : a unique UUID token to send to each request to identified the same request across callouts (for Google Billing)
   * @param			String countryFilters : Comma separated list of countries (2 digit codes) to filter the results
   * @return			Response wrapper with the isSuccess flag, errorMessage (if any) and the data from the callout response
   **********************************************************************************************************/
  @AuraEnabled
  public static Response getAddresses(String searchText, String sessionToken, String countryFilters) {
    String endpoint =
      settings.Place_Autocomplete_URL__c +
      '?input=' +
      EncodingUtil.urlEncode(searchText, 'UTF-8') +
      '&sessiontoken=' +
      sessionToken;

    // if we have country filters add them to the endpoint too
    if (String.isNotEmpty(countryFilters)) {
      String countriesToAdd = '';

      List<String> countries = countryFilters.split(',');
      for (String country : countries) {
        countriesToAdd += (String.isNotEmpty(countriesToAdd) ? '|' : '') + 'country:' + country.toLowerCase();
      }

      endpoint += '&components=' + countriesToAdd;
    }

    return doCallout(endpoint);
  }

  /*********************************************************************************************************
   * @name			getAddressDetails
   * @author			Pablo Martinez <ing.martinez.pablo@gmail.com>
   * @created			04 / 09 / 2022
   * @description		Method to get the full set of details from Google given a specific place_id
   * @param			String placeId : The place_id from Google obtained with the getAddresses method
   * @param			String sessionToken : a unique UUID token to send to each request to identified the same request across callouts (for Google Billing)
   * @return			Response wrapper with the isSuccess flag, errorMessage (if any) and the data from the callout response
   **********************************************************************************************************/
  @AuraEnabled
  public static Response getAddressDetails(String placeId, String sessionToken) {
    String endpoint =
      settings.Place_Details_URL__c +
      '?placeid=' +
      EncodingUtil.urlEncode(placeId, 'UTF-8') +
      '&sessiontoken=' +
      sessionToken;

    return doCallout(endpoint);
  }

  // wrapper class to return to the UI
  public class Response {
    @AuraEnabled
    public Boolean isSuccess;

    @AuraEnabled
    public String data;

    @AuraEnabled
    public String errorMessage;
  }
}